### ISSUE TITLE
BufferUnderflowException

### ISSUE THREAD

**Issue by vliedel** [dobots/bluenet-lib-android#1]
After some time of scanning, i get this crash:
```
07-27 14:09:12.668  32632-32632/nl.dobots.imbusy D/nl.dobots.imbusy.ImBusyApp﹕ Scanned E2:ED:6E:9C:31:AB (-76) MiniBeacon_06736
07-27 14:09:17.828  32632-32632/nl.dobots.imbusy D/AndroidRuntime﹕ Shutting down VM
07-27 14:09:17.908  32632-32632/nl.dobots.imbusy E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: nl.dobots.imbusy, PID: 32632
    java.nio.BufferUnderflowException
            at java.nio.ByteArrayBuffer.get(ByteArrayBuffer.java:152)
            at nl.dobots.bluenet.core.BleCore.parseAdvertisement(BleCore.java:614)
            at nl.dobots.bluenet.BleBase.access$000(BleBase.java:25)
            at nl.dobots.bluenet.BleBase$1.onData(BleBase.java:47)
            at nl.dobots.bluenet.core.BleCore$5.onLeScan(BleCore.java:602)
            at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:1825)
            at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:331)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
07-27 14:09:17.912     591-1229/system_process W/ActivityManager﹕ Force finishing activity 1 nl.dobots.imbusy/.MainActivity
07-27 14:09:27.924      591-630/system_process W/ActivityManager﹕ Activity destroy timeout for ActivityRecord{141fdf45 u0 nl.dobots.imbusy/.MainActivity t405 f}
```

**Comment by eggerdo** [comment]
added exception handling. happens if a wrong advertisement package format is received in which case we can't read company identifiers from the package.
